name: prava_vrecica

description: Project for LUMEN development competition.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.10.3+2

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.0.20
  animations: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.19

flutter:

  uses-material-design: true

flutter_native_splash:
  color: "#03a9f4"
  color_dark: "#0d47a1"
  android: true
  ios: true